Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "./install_docker.sh"

  (1..3).each do |i|
    config.vm.define "docker-#{i-1}" do |docker|

      config.vm.box = "ubuntu/focal64"
      config.vm.hostname = "docker#{i-1}"

      # config.vm.network "public_network", interface: "eno1", ip: "10.0.2.15"
      config.vm.network "private_network", ip: "192.168.56.#{i+1}"

      config.vm.provider "virtualbox" do |vb|
        vb.gui = false

        vb.memory = 1024

        vb.cpus = 1
      end
    end
  end

end